-- EUROPA ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('España','ESP'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Alemania','GER'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Austria','AUS'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Bélgica','BEL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Bulgaria','BUL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Dinamarca','DEN'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Francia','FRA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Finlandia','FIN'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Grecia','GRE'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Holanda','HOL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Hungría','HUN'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Irlanda','IRL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Italia','ITA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Letonia','LET'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Luxemburgo','LUX'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Noruega','NOR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Polonia','POL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Portugal','POR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Reino Unido','UKM'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('República Checa','RCH'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Rumanía','RUM'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Suecia','SUE'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Suiza','SWI'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Turquía','TUR'); 
commit;
-- AFRICA ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Egipto','EGI'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Marruecos','MAR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Sudáfrica','SUD'); 
commit;
-- AMERICA DEL NORTE ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Canadá','CAN'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Estados Unidos','USA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('México','MEX');
commit;
-- AMERICA CENTRAL ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Costa Rica','COR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('El Salvador','SAL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Guatemala','GUA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Honduras','HON'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Nicaragua','NIC'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Panamá','PAN'); 
commit;
-- CARIBE ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Cuba','CUB'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Antigua y Barbuda','AYB'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Aruba','ARU'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Bahamas','BAH'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Curazao','CUR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Jamaica','JAM'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Puerto Rico','PUE'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('República Dominicana','REP'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Saint Martin','SAI'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Santa Lucía','STL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Trinidad y Tobago','TYT'); 
commit;
-- AMERICA DEL SUR ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Argentina','ARG'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Bolivia','BOL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Brasil','BRA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Chile','CHI'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Colombia','COL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Ecuador','ECU'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Paraguay','PAR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Perú','PER'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Surinam','SUR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Uruguay','URU'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Venezuela','VEN'); 
commit;
-- ASIA ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Arabia Saudita','ARS'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('China','CHI'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Corea del Norte','NCO'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Corea del Sur','SCO'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Emiratos Árabes Unidos','EAU'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Filipinas','FIL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('India','IND'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Indonesia','IDO'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Irak','IRA'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Israel','ISR'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Japón','JAP'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Kuwait','KUW'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Líbano','LIB'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Malasia','MAL'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Rusia','RUS'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Singapur','SIN'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Tailandia','TAI'); 
commit;
-- OCEANIA ----------------------------------------------------------------------------------
insert into wiku_airlines.pais (nombre,acronimo) values ('Australia','AST'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Nueva Zelanda','NZE'); 
insert into wiku_airlines.pais (nombre,acronimo) values ('Polinesia Francesa','PFR'); 
commit;