insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(1,'Aeropuerto Adolfo Suárez Madrid-Barajas (MAD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(2,'Aeropuerto de Albacete (ABC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(3,'Aeropuerto de Alicante (ALC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(4,'Aeropuerto de Almería (LEI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(5,'Aeropuerto de Asturias (OVD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(6,'Aeropuerto de Badajoz (BJZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(7,'Aeropuerto de Barcelona (BCN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(8,'Aeropuerto de Bilbao (BIO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(9,'Aeropuerto de Burgos (RGS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(10,'Aeropuerto Central de Ciudad Real (CQM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(11,'Aeropuerto de Córdoba (ODB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(12,'Aeropuerto de El Hierro (VDE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(13,'Aeropuerto de Fuerteventura (FUE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(14,'Aeropuerto de Gerona-Costa Brava (GRO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(15,'Aeropuerto de Gran Canaria (LPA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(16,'Aeropuerto de Granada (GRX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(17,'Aeropuerto de Huesca – Pirineos (HSK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(18,'Aeropuerto de Ibiza (IBZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(19,'Aeropuerto de Jerez (XRY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(20,'Aeropuerto de La Coruña (LCG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(21,'Aeropuerto de La Gomera (GMZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(22,'Aeropuerto de La Palma (SPC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(23,'Aeropuerto de Lanzarote (ACE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(24,'Aeropuerto de León (LEN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(25,'Aeropuerto de Logroño-Agoncillo (RJL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(26,'Aeropuerto de Menorca (MAH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(27,'Aeropuerto de Málaga (AGP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(28,'Aeropuerto de Melilla (MLN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(29,'Aeropuerto de Murcia-San Javier (MJV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(30,'Aeropuerto de Palma de Mallorca (PMI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(31,'Aeropuerto de Pamplona (PNA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(32,'Aeropuerto de Reus (REU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(33,'Aeropuerto de Sadabell (QSA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(34,'Aeropuerto de San Sebastián (EAS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(35,'Aeropuerto de Santiago de Compostela (SCQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(36,'Aeropuerto de Salamanca (SLM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(37,'Aeropuerto de Santander (SDR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(38,'Aeropuerto de Sevilla (SVQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(39,'Aeropuerto de Tenerife Norte (TFN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(39,'Aeropuerto de Tenerife Sur (TFS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(40,'Aeropuerto de Valencia (VLC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(41,'Aeropuerto de Valladolid (VLL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(42,'Aeropuerto de Vigo (VGO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(43,'Aeropuerto de Vitoria (VIT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(44,'Aeropuerto de Zaragoza (ZAZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(45,'Aeropuerto de Berlín-Brandeburgo Willy Brandt (BER)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(45,'Aeropuerto de Berlí­n-Tegel (TXL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(45,'Aeropuerto de Berlí­n-Schönefeld (SXF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(46,'Aeropuerto de Karlsruhe / Baden-Baden (FKB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(47,'Aeropuerto de Friedrichshafen (FDH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(48,'Aeropuerto de la Ciudad de Mannheim (MHG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(49,'Aeropuerto de Stuttgart (STR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(50,'Aeropuerto de Bremen (BRE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(50,'Aeropuerto de Bremerhaven (BRV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(51,'Aeropuerto de Colonia/Bonn (CGN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(52,'Aeropuerto de Dortmund (DTM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(53,'Aeropuerto Internacional de Düsseldorf (DUS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(54,'Aeropuerto de Weeze (NRN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(55,'Aeropuerto de Münster/Osnabrück (FMO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(56,'Aeropuerto de Paderborn Lippstadt (PAD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(57,'Aeropuerto de Dresde (DRS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(58,'Aeropuerto de Erfurt (ERF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(59,'Aeropuerto de Leipzig-Halle (LEJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(59,'Aeropuerto de Leipzig-Altenburg (AOC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(60,'Aeropuerto de Frankfurt (FRA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(61,'Aeropuerto de Hamburgo-Fuhlsbüttel (HAM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(62,'Aeropuerto de Hanóver (HAJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(63,'Aeropuerto de Frankfurt-Hahn (HHN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(64,'Aeropuerto de Lübeck (LBC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(65,'Aeropuerto de Sylt (GWT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(66,'Aeropuerto de Memmingen (FMM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(67,'Aeropuerto de Múnich (MUC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(68,'Aeropuerto de Núremberg (NUE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(69,'Aeropuerto de Rostock-Laage (RLG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(70,'Aeropuerto de Saarbrücken (SCN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(71,'Aeropuerto Internacional de Viena (VIE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(72,'Aeropuerto de Graz (GRZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(73,'Aeropuerto de Salzburgo (SZG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(74,'Aeropuerto de Bruselas (BRU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(74,'Aeropuerto de Bruselas Sur (CRL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(75,'Aeropuerto de Amberes-Deurne (ANR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(76,'Aeropuerto de Liège (LGG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(77,'Aeropuerto de Sofía (SOF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(78,'Aeropuerto de Copenhague-Kastrup (CPH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(79,'Aeropuerto de Copenhague-Roskilde (RKE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(80,'Aeropuerto de Aalborg (AAL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(81,'Aeropuerto de Aarhus (AAR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(82,'Aeropuerto de Parí­s-Charles de Gaulle (CDG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(82,'Aeropuerto de Parí­s-Orly (ORY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(83,'Aeropuerto de Beauvais Tillé (BVA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(84,'Aeropuerto de Biarritz-Anglet-Bayonne (BIQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(85,'Aeropuerto de Burdeos-Merignac (BOD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(86,'Aeropuerto Internacional de Pau-Pirineos (PUF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(87,'Aeropuerto de Brest Bretagne (BES)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(88,'Aeropuerto Internacional de Estrasburgo (SXB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(89,'Aeropuerto de Basilea-Mulhouse-Friburgo (BSL,MLH,EAP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(90,'Aeropuerto Internacional de Lyon-Saint-Exupéry (LYS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(91,'Aeropuerto de Saint-Étienne – Bouthéon (EBU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(92,'Aeropuerto de Lille-Lesquin (LIL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(93,'Aeropuerto de Marsella Provenza (MRS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(94,'Aeropuerto de Niza Costa Azul (NCE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(95,'Aeropuerto de Montpellier-Méditerranée (MPL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(96,'Aeropuerto de Toulouse-Blagnac (TLS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(97,'Aeropuerto de Helsinki-Vantaa (HEL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(98,'Aeropuerto Internacional Eleftherios Venizelos (ATH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(99,'Aeropuerto de Ámsterdam-Schiphol (AMS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(100,'Aeropuerto de Eindhoven (EIN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(101,'Aeropuerto de Groningen Eelde (GRQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(102,'Aeropuerto de Róterdam (RTM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(103,'Aeropuerto de Budapest-Ferenc Liszt (BUD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(104,'Aeropuerto de Dublín (DUB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(105,'Aeropuerto Internacional de Shannon (SNN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(106,'Aeropuerto de Roma-Fiumicino (FCO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(106,'Aeropuerto de Roma-Ciampino (CIA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(107,'Aeropuerto de Alghero-Fertilia (AHO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(108,'Aeropuerto de Cagliari-Elmas (CAG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(109,'Aeropuerto de Ancona-Falconara (AOI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(110,'Aeropuerto de Bérgamo-Orio al Serio (BGY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(111,'Aeropuerto de Brescia (VBS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(112,'Aeropuerto de Milán-Linate (LIN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(112,'Aeropuerto de Milán-Malpensa (MXP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(113,'Aeropuerto de Bari-Palese (BRI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(114,'Aeropuerto de Reggio di Calabria (REG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(115,'Aeropuerto de Florencia (FLR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(116,'Aeropuerto de Génova (GOA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(117,'Aeropuerto de Nápoles-Capodichino (NAP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(118,'Aeropuerto de Parma-Giuseppe Verdi (PMF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(119,'Aeropuerto de Rímini (RMI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(120,'Aeropuerto de Bolonia (BLQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(121,'Aeropuerto de Forli (FRL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(122,'Aeropuerto de Palermo-Punta Raisi (PMO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(123,'Aeropuerto de Catania-Fontanarossa (CTA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(124,'Aeropuerto de Perugia (PEG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(125,'Aeropuerto Internacional Galileo Galilei (PSA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(126,'Aeropuerto de Turín-Caselle (TRN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(127,'Aeropuerto de Venecia-Marco Polo (VCE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(128,'Aeropuerto de Verona-Villafranca (VRN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(129,'Aeropuerto Internacional de Riga (RIX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(130,'Aeropuerto de Luxemburgo (LUX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(131,'Aeropuerto de Oslo-Gardermoen (OSL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(132,'Aeropuerto de Bergen-Flesland (BGO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(133,'Aeropuerto de Varsovia-Frédéric Chopin (WAW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(134,'Aeropuerto de Cracovia Juan Pablo II (KRK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(135,'Aeropuerto de Lisboa Portela (LIS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(136,'Aeropuerto Internacional de Faro (FAO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(137,'Aeropuerto de Lajes (TER)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(138,'Aeropuerto de Madeira (FNC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(139,'Aeropuerto Francisco Sá Carneiro (OPO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(140,'Aeropuerto Juan Pablo II (PDL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(141,'Aeropuerto de Edimburgo (EDI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(142,'Aeropuerto Internacional de Glasgow (GLA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(142,'Aeropuerto de Glasgow Prestwick (PIK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(143,'Aeropuerto de Ciudad de Londres (LCY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(144,'Aeropuerto de Londres-Gatwick (LGW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(145,'Aeropuerto de Londres-Heathrow (LHR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(146,'Aeropuerto de Londres-Luton (LTN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(147,'Aeropuerto de Londres-Oxford (OXF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(148,'Aeropuerto de Londres-Southend (SEN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(148,'Aeropuerto de Londres-Stansted (STN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(149,'Aeropuerto Internacional de Birmingham (BHX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(150,'Aeropuerto Internacional de Bristol (BRS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(151,'Aeropuerto Internacional de Liverpool (LPL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(152,'Aeropuerto de Mánchester (MAN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(153,'Aeropuerto Internacional de Newcastle (NCL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(154,'Aeropuerto de Gibraltar (GIB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(155,'Aeropuerto de Islas Caimán (GCM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(156,'Aeropuerto de Praga (PRG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(157,'Aeropuerto Internacional de Bucarest-Henri Coand? (OTP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(158,'Aeropuerto de Estocolmo-Arlanda (ARN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(158,'Aeropuerto de Estocolmo-Bromma (BMA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(158,'Aeropuerto de Estocolmo-Skavsta (NYO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(158,'Aeropuerto de Estocolmo-Västerås (VST)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(159,'Aeropuerto de Gotemburgo-Landvetter (GOT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(160,'Aeropuerto de Zúrich (ZRH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(161,'Aeropuerto de Berna (BRN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(162,'Aeropuerto Internacional de Ginebra (GVA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(163,'Aeropuerto Internacional Atatürk (IST)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(164,'Aeropuerto Internacional de El Cairo (CAI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(165,'Aeropuerto Internacional de Alejandría (ALY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(166,'Aeropuerto Internacional de Asuán (ASW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(167,'Aeropuerto Internacional de Hurghada (HRG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(168,'Aeropuerto Internacional de Luxor (LXR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(169,'Aeropuerto Internacional de Marsa Alam (RMF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(170,'Aeropuerto Internacional de Sharm el-Sheij (SSH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(171,'Aeropuerto Internacional de Taba (TCP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(172,'Aeropuerto Internacional Mohámmed V (CMN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(173,'Aeropuerto de Agadir-Al Massira (AGA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(174,'Aeropuerto de Alhucemas (AHU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(175,'Aeropuerto de Dajla (VIL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(176,'Aeropuerto Internacional de la Ciudad del Cabo (CPT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(177,'Aeropuerto de Johannesburgo (JNB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(178,'Aeropuerto Internacional de Ottawa/McDonald-Cartier (YOW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(179,'Aeropuerto de Grande Prairie (YQU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(179,'Aeropuerto Internacional de Calgary (YYC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(179,'Aeropuerto Internacional de Edmonton (YEG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(180,'Aeropuerto Internacional Pierre Elliott Trudeau (YUL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(180,'Aeropuerto Internacional de Montreal-Mirabel (YMX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(180,'Aeropuerto de Montreal-Saint-Hubert (YHU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(181,'Aeropuerto Internacional Ciudad de Quebec-Jean Lesage (YQB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(182,'Aeropuerto Internacional de San Juan de Terranova (YYT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(183,'Aeropuerto Internacional Toronto Pearson (YYZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(184,'Aeropuerto Internacional de Vancouver (YVR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(185,'Aeropuerto Internacional James Armstrong Richardson (YWG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(186,'Aeropuerto Internacional de Birmingham-Shuttlesworth (BHM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(187,'Aeropuerto Internacional Ted Stevens Anchorage (ANC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(188,'Aeropuerto de Kingman Arizona (IGM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(189,'Aeropuerto Internacional de Phoenix Sky Harbor (PHX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(190,'Aeropuerto Regional de Prescott (PRC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(191,'Aeropuerto Internacional de Tucson (TUS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(192,'Aeropuerto Internacional de Fresno Yosemite (FAT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(193,'Aeropuerto Regional LA/Palmdale (PMD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(193,'Aeropuerto Internacional de Los Ángeles (LAX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(194,'Aeropuerto de Long Beach (LGB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(195,'Aeropuerto Internacional de Oakland (OAK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(196,'Aeropuerto Internacional LA/Ontario (ONT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(197,'Aeropuerto John Wayne (SNA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(198,'Aeropuerto Internacional de Palm Springs (PSP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(199,'Aeropuerto Internacional de Sacramento (SMF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(200,'Aeropuerto Internacional de San Bernardino (SBD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(201,'Aeropuerto Internacional de San Diego (SAN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(201,'Aeropuerto McClellan-Palomar (CLD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(201,'Aeropuerto de Montgomery Field (MYF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(202,'Aeropuerto Internacional de San Francisco (SFO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(203,'Aeropuerto Internacional de San José (SJC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(204,'Aeropuerto Internacional de Charlotte-Douglas (CLT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(205,'Aeropuerto Internacional de Raleigh-Durham (RDU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(206,'Aeropuerto de Colorado Springs (COS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(207,'Aeropuerto Internacional de Denver (DEN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(208,'Aeropuerto Internacional de Daytona Beach (DAB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(209,'Aeropuerto Internacional Fort Lauderdale-Hollywood (FLL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(210,'Aeropuerto Internacional de Melbourne (MLB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(211,'Aeropuerto Internacional de Miami (MIA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(211,'Aeropuerto Internacional de Jacksonville (JAX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(211,'Aeropuerto Internacional Southwest Florida (RSW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(211,'Aeropuerto Internacional Sanford (SFB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(212,'Aeropuerto Internacional de Orlando (MCO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(213,'Aeropuerto Internacional de Tampa (TPA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(214,'Aeropuerto Internacional de Palm Beach (PBI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(215,'Aeropuerto Internacional Hartsfield-Jackson (ATL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(216,'Aeropuerto Internacional de Savannah/Hilton Head (SAV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(217,'Aeropuerto Internacional de Honolulu (HNL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(218,'Aeropuerto Internacional Chicago Midway (MDW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(218,'Aeropuerto Internacional Chicago-O’Hare (ORD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(219,'Aeropuerto Internacional de Indianápolis (IND)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(220,'Aeropuerto Internacional de Cincinnati/Kentucky Norte (CVG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(221,'Aeropuerto Internacional de Louisville (SDF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(222,'Aeropuerto Regional de Lafayette (LFT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(223,'Aeropuerto Internacional Louis Armstrong (MSY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(224,'Aeropuerto Internacional de Baltimore-Washington (BWI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(225,'Aeropuerto Internacional Logan (BOS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(226,'Aeropuerto Internacional de Detroit (DTW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(227,'Aeropuerto Internacional de Kalamazoo (AZO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(228,'Aeropuerto Internacional de Capital Region (LAN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(229,'Aeropuerto Internacional de Minneapolis-Saint Paul (MSP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(230,'Aeropuerto Internacional de Kansas City (MCI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(231,'Aeropuerto Internacional de Saint Louis-Lambert (STL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(232,'Aeropuerto Internacional McCarran (LAS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(233,'Aeropuerto Internacional de Buffalo Niagara (BUF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(234,'Aeropuerto Internacional Libertad de Newark (EWR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(235,'Aeropuerto Internacional John F. Kennedy (JFK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(235,'Aeropuerto LaGuardia (LGA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(235,'Aeropuerto Internacional de Albany (ALB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(236,'Aeropuerto Internacional de Albuquerque Sunport (ABQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(237,'Aeropuerto Internacional de Cleveland-Hopkins (CLE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(238,'Aeropuerto Internacional de Portland (PDX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(239,'Aeropuerto Internacional de Filadelfia (PHL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(240,'Aeropuerto Internacional de Memphis (MEM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(241,'Aeropuerto Internacional de Austin-Bergstrom (AUS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(242,'Aeropuerto de Dallas Love Field (DAL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(242,'Aeropuerto Internacional de Dallas-Fort Worth (DFW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(243,'Aeropuerto Internacional de Laredo (LRD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(244,'Aeropuerto Internacional de McAllen-Miller (MFE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(245,'Aeropuerto Intercontinental George Bush (IAH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(246,'Aeropuerto Internacional de Salt Lake City (SLC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(247,'Aeropuerto Municipal de St. George (SGU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(248,'Aeropuerto Internacional de Seattle-Tacoma (SEA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(249,'Aeropuerto Internacional Washington-Dulles (IAD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(249,'Aeropuerto Nacional Ronald Reagan de Washington (DCA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(250,'Aeropuerto Internacional General Mitchell (MKE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(251,'Aeropuerto de Rock Springs-Sweetwater County (RKS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(252,'Aeropuerto Internacional de la Ciudad de México (MEX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(253,'Aeropuerto Internacional Licenciado Jesús Terán Peredo (AGU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(254,'Aeropuerto Internacional General Rodolfo Sánchez Taboada (MXL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(255,'Aeropuerto Internacional de Tijuana (TIJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(256,'Aeropuerto Internacional Manuel Márquez de León (LAP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(257,'Aeropuerto Internacional de Los Cabos (SJD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(258,'Aeropuerto Internacional de Ciudad del Carmen (CME)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(259,'Aeropuerto Internacional Ángel Albino Corzo (TGZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(260,'Aeropuerto Internacional Abraham González (CJS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(261,'Aeropuerto Internacional General Roberto Fierro Villalobos (CUU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(262,'Aeropuerto Internacional General Guadalupe Victoria (DGO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(263,'Aeropuerto Internacional Lic. Adolfo López Mateos (TLC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(264,'Aeropuerto Internacional Del Bajío (BJX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(265,'Aeropuerto Internacional de Acapulco (ACA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(266,'Aeropuerto Internacional de Guadalajara (GDL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(267,'Aeropuerto Internacional de Puerto Vallarta (PVR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(268,'Aeropuerto Internacional de Uruapan (UPN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(269,'Aeropuerto Internacional General Francisco J. Mujica (MLM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(270,'Aeropuerto Internacional de Cuernavaca-Mariano Matamoros (CVJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(271,'Aeropuerto Internacional Mariano Escobedo (MTY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(272,'Aeropuerto Internacional de Oaxaca (OAX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(273,'Aeropuerto Internacional de Bahías de Huatulco (HUX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(274,'Aeropuerto Internacional de Puebla (PBC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(275,'Aeropuerto Internacional de Querétaro (QRO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(276,'Aeropuerto Internacional de Cancún (CUN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(277,'Aeropuerto Internacional de Cozumel (CZM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(278,'Aeropuerto Internacional Federal de Culiacán (CUL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(279,'Aeropuerto Internacional General Rafael Buelna (MZT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(280,'Aeropuerto Internacional Ponciano Arriaga (SLP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(281,'Aeropuerto Internacional de Hermosillo (HMO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(282,'Aeropuerto Internacional Carlos Rovirosa Pérez (VSA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(283,'Aeropuerto Internacional General Lucio Blanco (REX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(284,'Aeropuerto Internacional General Francisco Javier Mina (TAM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(285,'Aeropuerto Nacional El Tajín (PAZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(286,'Aeropuerto Internacional General Heriberto Jara (VER)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(287,'Aeropuerto Internacional Manuel Crescencio Rejón (MID)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(288,'Aeropuerto Internacional Juan Santamaría (SJO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(288,'Aeropuerto Internacional Tobías Bolaños (SYQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(289,'Aeropuerto Internacional Daniel Oduber Quirós (LIR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(290,'Aeropuerto Internacional de El Salvador (SAL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(291,'Aeropuerto Internacional La Aurora (GUA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(292,'Aeropuerto Internacional Mundo Maya (FRS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(293,'Aeropuerto Internacional Toncontín (TGU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(294,'Aeropuerto Internacional Golosón (LCE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(295,'Aeropuerto Internacional Ramón Villeda Morales (SAP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(296,'Aeropuerto Internacional Augusto C. Sandino (MGA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(297,'Aeropuerto Internacional de Tocumen (PTY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(297,'Aeropuerto Internacional Marcos A. Gelabert (PAC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(298,'Aeropuerto Internacional Enrique Malek (DAV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(299,'Aeropuerto Internacional V. C. Bird (MDQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(300,'Aeropuerto Internacional Reina Beatriz (AUA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(301,'Aeropuerto Internacional Lynden Pindling (NAS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(302,'Aeropuerto Internacional José Martí­ (HAV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(303,'Aeropuerto Juan Gualberto Gómez (VRA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(304,'Aeropuerto Internacional de Santiago de Cuba (SCU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(305,'Aeropuerto Internacional Hato (CUR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(306,'Aeropuerto Internacional Norman Manley (KIN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(307,'Aeropuerto Internacional de Sangster (MBJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(308,'Aeropuerto Internacional Luis Muñoz Marín (SJU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(309,'Aeropuerto Internacional Rafael Hernández (BQN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(310,'Aeropuerto José Aponte de la Torre (NRR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(311,'Aeropuerto Internacional Mercedita (PSE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(312,'Aeropuerto Antonio Rivera Rodríguez (VQS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(313,'Aeropuerto Internacional de Las Américas (SDQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(313,'Aeropuerto Internacional La Isabela (JBQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(314,'Aeropuerto Internacional María Montez (BRX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(315,'Aeropuerto Internacional de La Romana (LRM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(316,'Aeropuerto Internacional General Gregorio Luperón (POP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(317,'Aeropuerto Internacional de Punta Cana (PUJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(318,'Aeropuerto Internacional Presidente Juan Bosch (AZS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(319,'Aeropuerto Internacional del Cibao (STI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(320,'Aeropuerto Internacional Princesa Juliana (SXM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(321,'Aeropuerto Internacional Hewanorra (UVF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(322,'Aeropuerto Internacional de Piarco (POS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(323,'Aeropuerto Internacional Ministro Pistarini (EZE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(323,'Aeroparque Jorge Newbery (AEP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(324,'Aeropuerto Internacional Astor Piazolla (MDQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(325,'Aeropuerto Internacional Teniente Luis Candelaria (BRC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(326,'Aeropuerto Coronel Felipe Varela (CTC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(327,'Aeropuerto Internacional Ingeniero Ambrosio Taravella (COR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(328,'Aeropuerto Internacional Doctor Fernando Piragine Niveyro (CNQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(329,'Aeropuerto Internacional General Enrique Mosconi (CRD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(329,'Aeropuerto Internacional Brigadier General Antonio Parodi (EQS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(330,'Aeropuerto General Justo José de Urquiza (PRA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(331,'Aeropuerto Internacional de Formosa (FMA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(332,'Aeropuerto Internacional de Puerto Iguazú (IGU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(333,'Aeropuerto Internacional de Mendoza El Plumerillo (MDZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(333,'Aeropuerto Internacional Comodoro Ricardo Salomón (LGS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(334,'Aeropuerto Internacional Presidente Perón (NQN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(335,'Aeropuerto Internacional de Resistencia (RES)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(336,'Aeropuerto Internacional Rosario Islas Malvinas (ROS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(336,'Aeropuerto de Sauce Viejo (SFN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(337,'Aeropuerto Internacional de Salta Martín Miguel de Güemes (SLA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(338,'Aeropuerto de Río Grande (RGA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(338,'Aeropuerto Internacional de Ushuaia Malvinas Argentinas (USH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(339,'Aeropuerto Internacional de Tucumán (TUC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(340,'Aeropuerto Internacional El Alto (LPB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(341,'Aeropuerto Internacional Jorge Wilstermann (CBB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(342,'Aeropuerto Internacional Viru Viru (VVI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(343,'Aeropuerto Internacional de Brasilia (BSB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(344,'Aeropuerto Internacional de Rio Branco (RBR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(345,'Aeropuerto Internacional de Tabatinga (TBT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(346,'Aeropuerto Regional de Tefé (TFF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(347,'Aeropuerto Internacional Eduardo Gomes (MAO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(348,'Aeropuerto Internacional Deputado Luís Eduardo Magalhães (SSA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(349,'Aeropuerto Internacional Pinto Martins (FOR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(350,'Aeropuerto Eurico de Aguiar Salles (VIX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(351,'Aeropuerto Santa Genoveva (GYN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(352,'Aeropuerto Internacional Marechal Rondon (CGB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(353,'Aeropuerto Internacional de Belo Horizonte-Tancredo Neves (CNF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(354,'Aeropuerto Internacional de Belém (BEL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(355,'Aeropuerto Internacional de Curitiba Afonso Pena (CWB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(356,'Aeropuerto José Richa (LDB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(357,'Aeropuerto Regional Silvio Name Junior (MGF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(358,'Aeropuerto de Pampulha – Carlos Drummond de Andrade (PLU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(359,'Aeropuerto Internacional de Recife-Guararapes (REC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(360,'Aeropuerto Internacional de Galeão (GIG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(360,'Aeropuerto Santos Dumont (SDU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(361,'Aeropuerto Internacional Augusto Severo (NAT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(362,'Aeropuerto Internacional Salgado Filho (POA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(363,'Aeropuerto Governador Jorge Teixeira (PVH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(364,'Aeropuerto Internacional de São Paulo-Guarulhos (GRU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(364,'Aeropuerto de Congonhas São Paulo (CGH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(365,'Aeropuerto Internacional de Viracopos/Campinas (VCP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(366,'Aeropuerto Internacional Hercílio Luz (FLN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(367,'Aeropuerto Lauro Carneiro de Loyola (JOI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(368,'Aeropuerto Internacional de Aracaju (AJU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(369,'Aeropuerto Internacional Comodoro Arturo Merino Benítez (SCL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(370,'Aeropuerto Internacional Cerro Moreno (ANF)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(371,'Aeropuerto Internacional Chacalluta (ARI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(372,'Aeropuerto Internacional El Loa (CJC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(373,'Aeropuerto Internacional Carriel Sur (CCP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(374,'Aeropuerto La Florida (LSC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(375,'Aeropuerto Desierto de Atacama (CPO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(376,'Aeropuerto Internacional Diego Aracena (IQQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(377,'Aeropuerto Internacional Presidente Carlos Ibáñez del Campo (PUQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(378,'Aeropuerto Internacional El Tepual (PMC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(379,'Aeropuerto Internacional Mataveri (IPC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(380,'Aeropuerto La Araucanía (ZCO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(381,'Aeropuerto Internacional El Dorado (BOG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(382,'Aeropuerto Internacional José María Córdova (MDE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(382,'Aeropuerto Olaya Herrera (EOH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(383,'Aeropuerto Internacional Ernesto Cortissoz (BAQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(384,'Aeropuerto Internacional Rafael Núñez (CTG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(385,'Aeropuerto El Alcaraván (EYP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(386,'Aeropuerto Los Garzones (MTR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(387,'Aeropuerto El Caraño (UIB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(388,'Aeropuerto Benito Salas (NVA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(389,'Aeropuerto Internacional Simón Bolívar (SMR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(390,'Aeropuerto Internacional Camilo Daza (CUC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(391,'Aeropuerto Internacional El Edén (AXM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(392,'Aeropuerto Internacional Matecaña (PEI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(393,'Aeropuerto Nacional Yariguíes (EJA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(394,'Aeropuerto Internacional Palonegro (BGA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(395,'Aeropuerto Internacional Gustavo Rojas Pinilla (ADZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(396,'Aeropuerto Perales (IBE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(397,'Aeropuerto Gerardo Tobar López (BUN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(398,'Aeropuerto Internacional Alfonso Bonilla Aragón (CLO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(399,'Aeropuerto Internacional Mariscal Sucre (UIO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(399,'Aeropuerto Internacional de Quito (UIO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(400,'Aeropuerto Seymour de Baltra (GPS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(401,'Aeropuerto de San Cristóbal (SCY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(402,'Aeropuerto Internacional Cotopaxi – Latacunga (LTX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(403,'Aeropuerto Internacional Mariscal Lamar (CUE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(404,'Aeropuerto Internacional General Rivadeneira (ESM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(405,'Aeropuerto Internacional José Joaquín de Olmedo (GYE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(406,'Aeropuerto Camilo Ponce Enríquez – Loja (LOH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(407,'Aeropuerto Internacional Eloy Alfaro – Manta (MEC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(408,'Aeropuerto Coronel Edmundo Carvajal – Macas (XMS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(409,'Aeropuerto Francisco de Orellana (OCC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(410,'Aeropuerto General Ulpiano Paez (SNC)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(411,'Aeropuerto de Nueva Loja (LGQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(412,'Aeropuerto Internacional Silvio Pettirossi (ASU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(413,'Aeropuerto Internacional Guaraní (AGT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(414,'Aeropuerto Internacional Dr. Luis María Argaña (ESG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(415,'Aeropuerto Internacional Jorge Chávez (LIM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(416,'Aeropuerto de Chachapoyas (CHH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(417,'Aeropuerto Internacional Rodríguez Ballón (AQP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(418,'Aeropuerto Coronel FAP Alfredo Mendivil Duarte (AYP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(419,'Aeropuerto Mayor General FAP Armando Revoredo Iglesias (CJA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(420,'Aeropuerto Internacional Alejandro Velasco Astete (CUZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(421,'Aeropuerto Internacional Capitán FAP José A. Quiñones (CIX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(422,'Aeropuerto Internacional de Iquitos (IQT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(423,'Aeropuerto Internacional Capitán FAP Carlos Martínez de Pinillos (TRU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(424,'Aeropuerto Internacional de Puerto Maldonado (PEM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(425,'Aeropuerto Internacional Capitán FAP Guillermo Concha Iberico (PIU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(426,'Aeropuerto Internacional Inca Manco Cápac (JUL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(427,'Aeropuerto Cadete FAP Guillermo del Castillo Paredes (TPP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(428,'Aeropuerto Internacional Coronel FAP Carlos Ciriani Santa Rosa (TCQ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(429,'Aeropuerto Capitán FAP Pedro Canga Rodríguez (TBP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(430,'Aeropuerto Internacional Capitán FAP David Abensur Rengifo (PCL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(431,'Aeropuerto Internacional Johan Adolf Pengel (PBM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(432,'Aeropuerto Internacional de Carrasco (MVD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(433,'Aeropuerto Internacional de Artigas (ATI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(434,'Aeropuerto Internacional de Laguna del Sauce (PDP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(435,'Aeropuerto Internacional Presidente Gral Oscar Gestido (RVY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(436,'Aeropuerto Internacional de Maiquetí­a Simón Bolí­var (CCS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(437,'Aeropuerto Cacique Aramare (PYH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(438,'Aeropuerto Internacional General José Antonio Anzoátegui (BLA)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(439,'Aeropuerto Nacional de Barinas (BNS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(440,'Aeropuerto Parque Nacional Canaima (CAJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(441,'Aeropuerto Nacional Tomas de Heres (CBL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(442,'Aeropuerto de Santa Elena de Uairén (SNV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(443,'Aeropuerto Internacional Manuel Carlos Piar (PZO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(444,'Aeropuerto Internacional Arturo Michelena (VLN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(445,'Aeropuerto Internacional José Leonardo Chirino (CZE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(446,'Aeropuerto Internacional Josefa Camejo (LSP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(447,'Aeropuerto Internacional Jacinto Lara (BRM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(448,'Aeropuerto Alberto Carnevalli (MRD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(449,'Aeropuerto Internacional José Tadeo Monagas (MUN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(450,'Aeropuerto Internacional del Caribe Santiago Mariño (PMV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(451,'Aeropuerto Internacional Antonio José de Sucre (CUM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(452,'Aeropuerto Internacional de Santo Domingo (STD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(453,'Aeropuerto Internacional Juan Vicente Gómez (SVZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(454,'Aeropuerto Internacional de La Chinita (MAR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(455,'Aeropuerto Miguel Urdaneta Fernández (STB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(456,'Aeropuerto Internacional King Khalid (RUH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(457,'Aeropuerto Internacional Rey Abdulaziz (JED)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(458,'Aeropuerto Internacional de Pekín (PEK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(459,'Aeropuerto Internacional de Cantón Baiyun (CAN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(460,'Aeropuerto Internacional Foshan Shadi (FUO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(461,'Aeropuerto Internacional de Hong Kong (HKG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(462,'Aeropuerto Internacional de Shanghái Pudong (PVG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(463,'Aeropuerto Internacional de Taiwán Taoyuan (TPE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(464,'Aeropuerto Internacional de Tianjin Binhai (TSN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(465,'Aeropuerto Internacional de Xi’an Xianyang (XIY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(466,'Aeropuerto Internacional de Sunan (FNJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(467,'Aeropuerto Internacional de Incheon (ICN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(467,'Aeropuerto Internacional de Gimpo (GMP)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(468,'Aeropuerto Internacional de Jeju (CJU)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(469,'Aeropuerto Internacional de Abu Dhabi (AUH)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(470,'Aeropuerto Internacional de Dubái (DXB)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(471,'Aeropuerto Internacional de Sharjah (SHJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(472,'Aeropuerto Internacional Ninoy Aquino (MNL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(473,'Aeropuerto Internacional Indira Gandhi (DEL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(474,'Aeropuerto Internacional Chhatrapati Shivaji (BOM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(475,'Aeropuerto Internacional de Soekarno-Hatta (CGK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(476,'Aeropuerto Internacional de Bagdad (BGW)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(477,'Aeropuerto Internacional Ben Gurión (TLV)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(478,'Aeropuerto Internacional de Tokio (HND)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(479,'Aeropuerto Internacional de Narita (NRT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(480,'Aeropuerto de Fukuoka (FUK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(481,'Aeropuerto de Hakodate (HKD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(482,'Aeropuerto de Hiroshima (HIJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(483,'Aeropuerto de Ibaraki (IBR)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(484,'Aeropuerto de Ishigaki (ISG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(485,'Aeropuerto de Nagasaki (NGS)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(486,'Aeropuerto Internacional Chubu Centrair (NGO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(487,'Aeropuerto de Okayama (OKJ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(488,'Aeropuerto Internacional de Kansai (KIX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(488,'Aeropuerto Internacional de Osaka (ITM)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(489,'Aeropuerto Mt. Fuji Shizuoka (FSZ)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(490,'Aeropuerto Internacional de Kuwait (KWI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(491,'Aeropuerto Internacional Rafic Hariri de Beirut (BEY)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(492,'Aeropuerto Internacional de Kuala Lumpur (KUL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(493,'Aeropuerto Internacional de Penang (PEN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(494,'Aeropuerto Internacional Kota Kinabalu (BKI)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(495,'Aeropuerto Internacional de Moscú-Sheremetyevo (SVO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(495,'Aeropuerto Internacional de Moscú-Domodedovo (DME)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(495,'Aeropuerto Internacional de Moscú-Vnukovo (VKO)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(496,'Aeropuerto de Púlkovo-San Petersburgo (LED)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(497,'Aeropuerto de Singapur (SIN)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(498,'Aeropuerto Internacional de Bangkok (BKK)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(499,'Aeropuerto Internacional de Chiang Mai (CNX)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(500,'Aeropuerto Internacional de Phuket (HKT)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(501,'Aeropuerto de Brisbane (BNE)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(502,'Aeropuerto de Melbourne (MEL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(503,'Aeropuerto de Sí­dney (SYD)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(504,'Aeropuerto Internacional de Auckland (AKL)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(505,'Aeropuerto Internacional de Wellington (WLG)');
insert into wiku_airlines.aeropuerto (id_ciudad,nombre)values(506,'Aeropuerto Internacional Faa’a (PPT)');
commit;