server:
  port: 8080
  servlet:
    context-path: /wikuairlines
logging:
  level:
    org.springframework: ERROR
    com.camaras: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
#===========================================================================#
#--------------------------------- Spring ----------------------------------#
#===========================================================================#
spring:
  mvc:
    favicon:
      enabled: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/wiku_airlines?serverTimezone=UTC
    username: root
    password: root
