server:
  port: 8080
  servlet:
    context-path: /wikuairlines
#logging:
#  config:
#===========================================================================#
#--------------------------------- Spring ----------------------------------#
#===========================================================================#
spring:
  mvc:
    favicon:
      enabled: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/medeor?serverTimezone=UTC
    username: root
    password: root
